language: node_js
node_js:
- '0.8'
- '0.10'
before_install:
- curl -L http://git.io/ejPSng | /bin/sh
notifications:
  slack:
    secure: YF+wlxp5ylbtbsJUkDrghfdHURZ5Oj3MOjwLNeSqK3kMTsCPLBKIDIF4t33jKoeZ6Wciid0c+x7VZjdaMolUBO5dzzK4sVUmMKrt7p+xhJX5Df1jKZLYsE/Y7LSuOKl5Jnr07agEOrPUZ8lI0M0JHIClsdl36lWxgOpbkST+d+Y=
